service: prepper-http-endpoints

provider:
  name: aws
  runtime: nodejs12.x
  stage: stage
  region: us-east-1

plugins:
  - serverless-webpack

functions:
  addToNewsletter:
    handler: server/handler.addToNewsletter
    events:
      - http:
          path: newletter
          method: post
          cors: true